import { beforeAll, describe, expect, it } from 'vitest';
import { deboilerplate, detectPagination, ingestPdf, repairLineBreaks } from '../ingest';
import type { ParsedDocument, TextLine } from '../types';
import { loadDerivedCorpus, loadSourceCorpus } from './helpers';

/**
 * Ingestion is where most demos of this kind fail, so it is tested against the
 * real generated PDFs rather than against a fixture of already-clean text.
 * Every page of the corpus carries a rotated bilingual watermark, a rotated
 * margin stamp, a running header, a running footer, and a printed page number
 * that does not agree with the PDF page number.
 */

let documents: Map<string, ParsedDocument>;

beforeAll(async () => {
  const parsed = await Promise.all(
    loadDerivedCorpus().map((file) => ingestPdf(file.descriptor, file.data)),
  );
  documents = new Map(parsed.map((d) => [d.type, d]));
}, 60_000);

describe('de-boilerplating', () => {
  it('drops the rotated watermark and margin stamp from every document', () => {
    for (const document of documents.values()) {
      expect(document.rotatedItemsDropped).toBeGreaterThan(document.pdfPageCount);
    }
  });

  it('leaves no watermark fragment anywhere in the extracted text', () => {
    for (const document of documents.values()) {
      for (const section of document.sections) {
        for (const paragraph of section.paragraphs) {
          expect(paragraph.text).not.toMatch(/DEMONSTRATION CORPUS|DEMONSTRATION DERIVE/i);
          expect(paragraph.text).not.toMatch(/Synthetic corpus - generated by/i);
        }
      }
    }
  });

  it('derives the running header and footer rather than being told them', () => {
    const sap = documents.get('SAP')!;
    expect(sap.boilerplate.some((line) => /Calibra Biologics/.test(line))).toBe(true);
    expect(sap.boilerplate.some((line) => /Page \d+ of \d+/.test(line))).toBe(true);
  });

  it('leaves no header or footer text inside a paragraph', () => {
    for (const document of documents.values()) {
      for (const section of document.sections) {
        for (const paragraph of section.paragraphs) {
          expect(paragraph.text).not.toMatch(/Page \d+ of \d+/);
          // The running footer is "Protocol CB207-C301 ... CONFIDENTIAL". The
          // word alone is legitimate cover-page text and stays.
          expect(paragraph.text).not.toMatch(/Protocol CB207-C301[^.]*CONFIDENTIAL/);
        }
      }
    }
  });

  it('keeps a redaction visible instead of deleting it', () => {
    const sap = documents.get('SAP')!;
    const all = sap.sections.flatMap((s) => s.paragraphs.map((p) => p.text)).join(' ');
    expect(all).toContain('[REDACTED]');
  });

  it('detects repeated lines by shape, so a changing page number does not defeat it', () => {
    const pages: TextLine[][] = [1, 2, 3, 4, 5].map((pdfPage) => [
      { text: `Page ${pdfPage} of 5`, x: 250, y: 52, fontSize: 8, mono: false, pdfPage },
      {
        text: `Body text about ${['alpha', 'beta', 'gamma', 'delta', 'epsilon'][pdfPage - 1]}.`,
        x: 68,
        y: 700,
        fontSize: 9.5,
        mono: false,
        pdfPage,
      },
    ]);
    const result = deboilerplate(pages);
    expect(result.boilerplate.some((line) => /Page \d+ of 5/.test(line))).toBe(true);
    expect(result.pages.every((lines) => lines.length === 1)).toBe(true);
  });
});

describe('pagination', () => {
  it('detects a printed-to-PDF offset per document rather than assuming one', () => {
    const offsets = [...documents.values()].map((d) => d.pageOffset);
    for (const offset of offsets) expect(offset).toBeGreaterThan(0);
    expect(new Set(offsets).size).toBeGreaterThan(1);
  });

  it('reports both page numbers, and they differ by the detected offset', () => {
    for (const document of documents.values()) {
      for (const section of document.sections) {
        if (section.printedPage === null) continue;
        expect(section.pdfPage - section.printedPage).toBe(document.pageOffset);
      }
    }
  });

  it('leaves the printed page null on front matter rather than inventing one', () => {
    const sap = documents.get('SAP')!;
    const cover = sap.sections[0];
    expect(cover.printedPage).toBeNull();
    expect(cover.pdfPage).toBe(1);
  });

  it('ignores a page-like phrase in the body of a page', () => {
    const pages: TextLine[][] = [
      [
        { text: 'see page 3 of the appendix', x: 68, y: 700, fontSize: 9.5, mono: false, pdfPage: 1 },
        { text: 'Page 1 of 1', x: 250, y: 52, fontSize: 8, mono: false, pdfPage: 1 },
      ],
    ];
    expect(detectPagination(pages).printedByPdfPage.get(1)).toBe(1);
  });
});

describe('structure', () => {
  it('rebuilds the numbered section tree including sub-sections and appendices', () => {
    const sap = documents.get('SAP')!;
    const ids = sap.sections.map((s) => s.id);
    for (const id of ['1', '2.3', '3.1', '5.5', '11.2.3', '12.1', 'APPENDIX 3', 'APPENDIX 9']) {
      expect(ids).toContain(id);
    }
  });

  it('keeps code appendices as line-structured blocks', () => {
    const sap = documents.get('SAP')!;
    const appendix = sap.sections.find((s) => s.id === 'APPENDIX 3')!;
    const code = appendix.paragraphs.filter((p) => p.kind === 'CODE');
    expect(code.length).toBeGreaterThan(0);
    expect(code.some((p) => p.lines.some((l) => /proc freq data=eff;/.test(l)))).toBe(true);
    expect(code.some((p) => p.lines.some((l) => /^\s*8\s*$/.test(l)))).toBe(true);
  });

  it('keeps table rows separable so totals can be recomputed', () => {
    const sap = documents.get('SAP')!;
    const disposition = sap.sections.find((s) => s.id === '5.2')!;
    const lines = disposition.paragraphs.flatMap((p) => p.lines);
    expect(lines.some((l) => /^Eastern Europe\s+34\s+34\s+68$/.test(l))).toBe(true);
    expect(lines.some((l) => /^Total\s+406\s+405\s+811$/.test(l))).toBe(true);
  });

  it('reads the abbreviation table out of the document', () => {
    const sap = documents.get('SAP')!;
    const acronyms = sap.abbreviations.map((a) => a.acronym);
    expect(acronyms).toContain('ATCC');
    expect(acronyms.filter((a) => a === 'PR')).toHaveLength(2);
    expect(sap.abbreviations.find((a) => a.acronym === 'pCR')?.expansion).toMatch(
      /pathologic complete response/i,
    );
  });

  it('reflows prose into whole sentences', () => {
    const sap = documents.get('SAP')!;
    const teae = sap.sections.find((s) => s.id === '12.1')!;
    expect(
      teae.paragraphs.some((p) =>
        /For the adjuvant period, a treatment-emergent adverse event is defined/.test(p.text),
      ),
    ).toBe(true);
  });

  it('repairs hyphenated line breaks', () => {
    expect(repairLineBreaks(['pharmaco-', 'kinetic sampling'])).toBe('pharmacokinetic sampling');
    expect(repairLineBreaks(['the first line', 'the second line'])).toBe(
      'the first line the second line',
    );
  });
});

/**
 * The real disclosure documents are an engineering fixture and are gitignored.
 * When somebody drops one into corpus/source/ these run; otherwise they skip,
 * so a clean checkout is still green.
 */
describe('source corpus (skipped when corpus/source is empty)', () => {
  const files = loadSourceCorpus();
  const maybe = files.length > 0 ? it : it.skip;

  maybe('parses every source PDF without watermark fragments', async () => {
    for (const file of files) {
      const document = await ingestPdf(file.descriptor, file.data);
      expect(document.sections.length).toBeGreaterThan(0);
      const text = document.sections.flatMap((s) => s.paragraphs.map((p) => p.text)).join(' ');
      expect(text).not.toMatch(/non-commercial purposes and subject to the Terms of Use/i);
    }
  }, 120_000);

  maybe('detects a printed-to-PDF offset in the source PDF', async () => {
    for (const file of files) {
      const document = await ingestPdf(file.descriptor, file.data);
      expect(document.printedPageCount).toBeGreaterThan(0);
    }
  }, 120_000);
});
